version: '3'

services:
  react_cassandra:
    #image: spotify/cassandra:latest (2.0.1)
    image: cassandra:3.11.2
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_CLUSTER_NAME=RagnaCluster
    ports:
      - 9160:9160
      - 9042:9042

  react_helenos:
    image: emdem/helenos
    ports:
      - 9000:8080
    links:
      - "react_cassandra:cassandra"
